language: c

branches:
   only:
      - master

services:
   - docker

matrix:
   include:
      - os: linux
        env:
         - FILENAME=steamsky-dev-Linux-64.tar.gz
        install:
         - docker pull thindil/gnat-gtkada;
        script:
         - docker run -v $(pwd):/app thindil/gnat-gtkada /bin/sh -c "cd /app && others/build.sh"
         - tar -czf steamsky-dev-Linux-64.tar.gz usr
      - os: windows
        env:
         - FILENAME=steamsky-dev-Windows-64.zip
        install:
         - export "PATH=/c/GNAT/bin:/c/GtkAda/bin:$PATH";
         - export "GPR_PROJECT_PATH=/c/GtkAda/lib/gnat";
         - wget "https://www.dropbox.com/s/2kk2hb6fvpy9a58/gnat.7z?dl=0" -O gnat.7z;
         - 7z x gnat.7z -oc:/;
         - wget "https://www.dropbox.com/s/jd0s4gkycrxy029/gtkada.7z?dl=0" -O gtkada.7z;
         - 7z x gtkada.7z -oc:/;
        script:
         - gprbuild -P steamsky.gpr -XMode=release
         - 7z a -tzip steamsky-dev-Windows-64.zip bin;

before_deploy:
    - "if [[ $FILENAME == \"steamsky-dev-Linux-64.tar.gz\" ]]; then git tag -f travis-dev-build && git remote add gh https://${TRAVIS_REPO_SLUG%/*}:${KEY}@github.com/${TRAVIS_REPO_SLUG}.git && git push -f gh travis-dev-build && git remote remove gh; fi"
    - export "TRAVIS_TAG=travis-dev-build";

deploy:
  provider: releases
  skip_cleanup: true
  api-key: $KEY
  file:
   - $FILENAME
  name: Continuous Integration build
  body: Development build of $TRAVIS_BRANCH built by Travis CI.
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  tag_name: travis-dev-build
  on:
   branch: master

notifications:
  email: false
